services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    ports:
      - '3306:3306'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_myapp
      - MARIADB_DATABASE=bitnami_myapp
  myapp:
    image: docker.io/bitnami/symfony:6.4
    ports:
      - '8007:8000'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=bn_myapp
      - DB_DATABASE=bitnami_myapp
      - SYMFONY_PROJECT_SKELETON=symfony/skeleton
    volumes:
      - './app:/app'
    depends_on:
      - mariadb
  myapp-worker:
    image: docker.io/bitnami/symfony:6.4
    depends_on:
      - mariadb
    volumes:
      - './app:/app'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=bn_myapp
      - DB_DATABASE=bitnami_myapp
      - SYMFONY_PROJECT_SKELETON=symfony/skeleton
    command: php bin/console messenger:consume async -vv